// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYZD0bGzf6DzsWEqRs8JgNmN5wkg0mhk',
    appId: '1:912237154118:web:21619af5c0ca8a1d705f47',
    messagingSenderId: '912237154118',
    projectId: 'expense-login-cc576',
    authDomain: 'expense-login-cc576.firebaseapp.com',
    storageBucket: 'expense-login-cc576.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcXfnTkuVTjxxLMPYqUFGSEA99Ul-VbVs',
    appId: '1:912237154118:android:e229b3cc508e3661705f47',
    messagingSenderId: '912237154118',
    projectId: 'expense-login-cc576',
    storageBucket: 'expense-login-cc576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3ue_zpPrSGDdeqwlsMYnY-GCuJSmYUM',
    appId: '1:912237154118:ios:abe3712694abe492705f47',
    messagingSenderId: '912237154118',
    projectId: 'expense-login-cc576',
    storageBucket: 'expense-login-cc576.appspot.com',
    iosClientId: '912237154118-5vq0i7an0ug228hgmm5fglm9b9c50j07.apps.googleusercontent.com',
    iosBundleId: 'com.example.exptracker',
  );
}
